name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Static Web to GCS
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      BUCKET_NAME: gcr-website-bucket
      TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
      TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Seed DB with Turso
        run: pnpm run seed

      - name: Build Astro
        run: pnpm run build

      - name: Clear bucket before upload
        run: gsutil -m rm -r gs://${{ env.BUCKET_NAME }}/** || true

      - name: Upload to GCS
        run: gsutil -m rsync -r -d -c dist/ gs://${{ env.BUCKET_NAME }}/

      - name: Set Web Index
        run: gsutil web set -m index.html -e 404.html gs://${{ env.BUCKET_NAME }}

      - name: Fix JS MIME types
        run: |
          echo "⏳ Waiting for files to sync..."
          sleep 10
          JS_FILES=$(gsutil ls gs://${{ env.BUCKET_NAME }}/_astro/*.js || true)
          if [ -n "$JS_FILES" ]; then
            gsutil -m setmeta -h "Content-Type:application/javascript" $JS_FILES
          else
            echo "⚠️ No JS files found to set MIME type."
          fi
