name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Static Web to GCS
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      BUCKET_NAME: gcr-website-bucket

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Seed DB with Turso
        run: |
          TURSO_DATABASE_URL=${{ secrets.TURSO_DATABASE_URL }} \
          TURSO_AUTH_TOKEN=${{ secrets.TURSO_AUTH_TOKEN }} \
          pnpm run seed

      - name: Build Astro
        run: pnpm run build

      - name: Sleep to wait for file consistency
        run: sleep 10

      - name: Clear GCS bucket
        run: gsutil -m rm -r gs://${{ env.BUCKET_NAME }}/** || true

      - name: Upload files to GCS
        run: gsutil -m rsync -r -d -c dist/ gs://${{ env.BUCKET_NAME }}/

      - name: Set Web Index & 404 page
        run: gsutil web set -m index.html -e 404.html gs://${{ env.BUCKET_NAME }}

      - name: Fix JS MIME types
        run: |
          js_files=$(gsutil ls gs://${{ env.BUCKET_NAME }}/_astro/*.js || true)
          if [[ -n "$js_files" ]]; then
            gsutil -m setmeta -h "Content-Type:application/javascript" $js_files
          else
            echo "No JS files found to update MIME type."
          fi
